export const ADD_TASK_PENDING = "ADD_TASK_PENDING";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_FAILUTE = "ADD_TASK_FAILUTE";
export const DELETE_TASK_PENDING = "DELETE_TASK_PENDING";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAILURE = "DELETE_TASK_FAILURE";
export const MARK_COMPLETE_TASK_PENDING = "MARK_COMPLETE_TASK_PENDING";
export const MARK_COMPLETE_TASK_SUCCESS = "MARK_COMPLETE_TASK_SUCCESS";
export const MARK_COMPLETE_TASK_FAILURE = "MARK_COMPLETE_TASK_FAILURE";

export const ADD_RANDOM_NAMES_REQUEST = "ADD_RANDOM_NAMES_REQUEST";
export const ADD_RANDOM_NAMES_SUCCESS = "ADD_RANDOM_NAMES_SUCCESS";
export const ADD_RANDOM_NAMES_FAILURE = "ADD_RANDOM_NAMES_FAILURE";