import { createTypes } from 'reduxsauce'

export default createTypes(`
    ADD_TASK_PENDING 
    ADD_TASK_SUCCESS 
    ADD_TASK_FAILUTE 
    DELETE_TASK_PENDING
    DELETE_TASK_SUCCESS
    DELETE_TASK_FAILURE
    MARK_COMPLETE_TASK_PENDING
    MARK_COMPLETE_TASK_SUCCESS
    MARK_COMPLETE_TASK_FAILURE
    
    ADD_RANDOM_NAMES_REQUEST
    ADD_RANDOM_NAMES_SUCCESS
    ADD_RANDOM_NAMES_FAILURE
`)
